algoritmo "Aula 4"

var

 N1, N2, N3: real
 Blz: caractere

inicio
 Escreva ("Vou ver pra tu se um número é maior que outro chefia. Blz? " )
 Leia (Blz)
 Escreva ("Fala um número ai zé: ")
 Leia (N1)
 Escreva ("Fala outro número ai patrão: ")
 Leia (N2)
 Escreva ("Só mais um rei: ")
 Leia (N3)
 Escreva ("Mue chegado! É ", N1>N2, " que ", N1, " é maior que ", N2, " e é ", N2<N3, " que ", N2, " é menor que ", N3,  " E também é ", N3>N1, " que ", N3, " é maior que ", N1. )

fimalgoritmo